# Generated by Django 5.2.6 on 2025-09-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='specfile',
            field=models.FileField(blank=True, null=True, upload_to='specs/'),
        ),
    ]
