# Generated by Django 5.2.6 on 2025-10-27 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_picture_product_specfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn13', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('publish_year', models.PositiveIntegerField(blank=True, null=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='myapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('condition_note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_LOAN', 'On loan'), ('LOST', 'Lost'), ('REPAIR', 'Repair')], default='AVAILABLE', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='myapp.book')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('renew_count', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='myapp.bookcopy')),
            ],
            options={
                'ordering': ['-checked_out_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_at', None)), fields=('copy', 'returned_at'), name='unique_active_loan_per_copy')],
            },
        ),
    ]
