# Generated by Django 5.2.6 on 2025-10-27 12:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_fine_hold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_loan_limit', models.PositiveIntegerField(default=5)),
                ('lecturer_loan_limit', models.PositiveIntegerField(default=10)),
                ('student_loan_days', models.PositiveIntegerField(default=14)),
                ('lecturer_loan_days', models.PositiveIntegerField(default=28)),
                ('fine_rate_per_day', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
