# Generated by Django 5.2.6 on 2025-10-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_bookcopy_status_cart_pickuprequest_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/books/'),
        ),
        migrations.DeleteModel(
            name='Hold',
        ),
    ]
