# Generated by Django 5.2.5 on 2025-11-27 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('ON_LOAN', 'On loan'), ('LOST', 'Lost'), ('REPAIR', 'Repair')], db_index=True, default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='returned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('READY', 'Ready for pickup'), ('PICKED_UP', 'Picked up'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='myapp_book_title_9d2a56_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category', '-id'], name='myapp_book_categor_e0b716_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['status', 'book'], name='myapp_bookc_status_6f8f48_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'name'], name='myapp_categ_parent__7dba1c_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower', '-checked_out_at'], name='myapp_loan_borrowe_d2ee02_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['returned_at', 'due_at'], name='myapp_loan_returne_223ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuprequest',
            index=models.Index(fields=['status', '-requested_at'], name='myapp_picku_status_062875_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuprequest',
            index=models.Index(fields=['requester', '-requested_at'], name='myapp_picku_request_0a6997_idx'),
        ),
    ]
